jwt:
  secret: peanut
data:
  filename: sample.csv
  disabled: false
#spring:
#  data:
#    mongodb:
#      database: sample
#      username: test
#      password: test123
#      authentication-database: admin
#      repositories:
#        type: auto
#      uri: mongodb://203.224.132.90/sample
spring:
  mongodb:
    embedded:
      storage:
        database-dir: "mongodb"
logging:
  file: union.log
  path: ./logs
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    level:
      root: info